### ISSUE TITLE
Flash from Octoprint without bootloader on electronics board

### ISSUE THREAD

**Issue by rraymakers** [OctoPrint/OctoPrint-FirmwareUpdater#71]
I found this guide https://learn.adafruit.com/program-an-avr-or-arduino-using-raspberry-pi-gpio-pins/overview and am wondering if it is possible to use this plugin through octopi to update the firmware of a board that has no bootloader on it.

**Comment by benlye** [comment]
I added linuxgpio as a programmer in the last release. If you follow the steps in the guide you linked to set up avrdude and the relevant parts of the conf file you should be all set. 

The only thing I would do differently is call the programmer 'linuxgpio' instead of 'pi_1', as that's the name the plugin is coded to call with the -c parameter. 

Let me know how it goes. I'll try it myself in the next day or two if I get a chance.
